// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6fisNmxX38LKwaF5MiST6DDtD5w75HqY',
    appId: '1:731485369722:web:b92b19314508be4e1bd2c3',
    messagingSenderId: '731485369722',
    projectId: 'uh-universe',
    authDomain: 'uh-universe.firebaseapp.com',
    storageBucket: 'uh-universe.appspot.com',
    measurementId: 'G-V4Z4S323M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP6ExP-nFU6_vDb6LDhBkjBxQJyGxS0T8',
    appId: '1:731485369722:android:e0b613fbf5460aa71bd2c3',
    messagingSenderId: '731485369722',
    projectId: 'uh-universe',
    storageBucket: 'uh-universe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC47BgYMtKVkHV1SxAps5aCU3vQ9LtJXao',
    appId: '1:731485369722:ios:e5d0f43335401af81bd2c3',
    messagingSenderId: '731485369722',
    projectId: 'uh-universe',
    storageBucket: 'uh-universe.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC47BgYMtKVkHV1SxAps5aCU3vQ9LtJXao',
    appId: '1:731485369722:ios:c00e9379f7c3eae81bd2c3',
    messagingSenderId: '731485369722',
    projectId: 'uh-universe',
    storageBucket: 'uh-universe.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
